# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  server:
    container_name: server
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8081:8080
    volumes:
      - .:/usr/app
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    mem_limit: 800m
    cpus: 1.5
    logging:
      options:
        max-size: 10m

  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=example
    ports:
      - 5436:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: 10m
volumes:
  db-data:
